### ISSUE TITLE
How does go-ia download files?

### ISSUE THREAD

**Issue by w0nd3r365** [nektro/go-internetarchive#6]
```
┌──(w0nd3r365@termux)-[/d/d/c/f/h/misc]
└─$ ./go-ia download https://archive.org/download/tiny11-2311/tiny11%202311%20x64.iso
2024/01/21 18:20:49 Complete after 1 tasks and 0 B downloaded.
```
This doesn't download any file. I've tried several other links with similar outcome. Am I using the wrong cmdline syntax.
Better documentation with sample use cases would be really helpful, but I haven't found any.

Also, of noteworthy concern is that the time indicated by go-ia logs is GMT+0 rather than my actual timezone GMT+3.

**Comment by nektro** [comment]
the accepted input would be `./go-ia download tiny11-2311`. the param accepts item and collection names not specific urls. if a single file is your goal u might be better served using `wget`.

**Comment by w0nd3r365** [comment]
Thanks, using the collection name works now. I don't really know what's wrong, but after several successful download attempts using `go-ia` it just stopped working at all out of the blue, when using the right syntax.
```
┌──(w0nd3r365@termux)-[/d/d/c/f/h/misc]
└─$ ./go-ia download tiny11-2311
2024/01/21 20:40:44 Complete after 1 tasks and 0 B downloaded.
```
Anyway, I came across this project in reddit when researching how to speed up downloads from archive.org. I'll try `aria2c` multithreaded downloads because I want to download specific urls only, not entire collections. Maybe @nektro can add to this project's todo downloading specific archive.org urls.

I'll close this issue for now since it's primary question has been addressed.

**Comment by nektro** [comment]
in order to save on network there's a number of mechanisms it uses to check if the files are already saved locally. if its not downloading files you expect to be there try deleting the folder and running it again

**Comment by w0nd3r365** [comment]
Yeah, you're right. There were partially downloaded files that prevented `go-ia` from downloading the files. I assumed the default output directory used by `go-ia` would be `./<collection_name>` rather than `./data/<collection_name>`. Since I had a pre-existing `./data` dir, I didn't think to look there. But then from the `go-ia` usage info I learnt it saved in `./data`.

@nektro I think that a person normally expects a program downloading files to save in the working dir without creating an extra subfolder like `./data`. Also, more descriptive error handling would have aided in easier debugging, like `E: File exists (17): skipping download`, `E: Invalid URI: can't find requested item`, with appropriate non-zero exit codes.Also, I think it would be better to autoresume a partial download, informing the user like, `W: Resuming partially downloaded file`, after comparing the length of local file with the remote one. So in consequence, replace `--resume` flag to `download` subcommand with `--no-resume`. Sorry, I could have helped but I don't know golang.
